image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cabal update
      stack build
    command: |
      python -m http.server 8000
vscode:
  extensions:
    - haskell.haskell
    - dhall.dhall-lang
